import {type Blueprint, Parser, type SaveEntity} from '@etothepii/satisfactory-file-parser'
import {Sign} from '../../scripts/lib/buildable.ts'
import JSZip from 'jszip'
import {Buffer} from 'buffer'

let blueprintCache: Blueprint | null = null

async function fetchTemplateBlueprint(): Promise<Blueprint> {
  if (!blueprintCache) {
    let response: Response

    response = await fetch(`${import.meta.env.BASE_URL}/bps/4m-label.sbp`)

    if (!response.ok) {
      throw new Error(`Failed to fetch 4m-label.sbp: ${response.statusText}`)
    }
    const sbpBuffer = await response.arrayBuffer()

    response = await fetch(`${import.meta.env.BASE_URL}/bps/4m-label.sbpcfg`)
    if (!response.ok) {
      throw new Error(`Failed to fetch 4m-label.sbp: ${response.statusText}`)
    }

    const sbpcfgBuffer = await response.arrayBuffer()

    console.log('Loaded blueprint files:', {
      sbpSize: sbpBuffer.byteLength,
      sbpcfgSize: sbpcfgBuffer.byteLength
    })

    blueprintCache = Parser.ParseBlueprintFiles(
      '4m-label',
      sbpBuffer,
      sbpcfgBuffer,
    )
  }

  return blueprintCache
}

export class BpGenerator {
  private readonly SIGN_HEIGHT = 50
  private readonly SIGN_WIDTH = 400
  private readonly SIGNS_PER_BP = 40
  private readonly SIGNS_PER_BP_ROW = 2

  public constructor(private readonly templateBlueprint: Blueprint) {
  }

  static async create(): Promise<BpGenerator> {
    return new BpGenerator(await fetchTemplateBlueprint())
  }

  public* blueprints(points: number[]): Generator<Blueprint, void, unknown> {

    let blueprint: Blueprint | null = null
    let keySign: Sign | null = null
    let signIndex: number = 0
    let bpIndex: number = 1

    // remove c0 controls
    points = points.filter(p => p >= 0x0020)

    const rows = this.pointsToRows(points)

    while (rows.length > 0) {
      const row1 = rows.shift() || []
      const row2 = rows.shift() || []

      if (!blueprint || !keySign) {
        blueprint = JSON.parse(JSON.stringify(this.templateBlueprint)) as Blueprint
        keySign = new Sign(blueprint.objects.pop() as SaveEntity)
        signIndex = 1

        keySign = keySign
          .withText(`Generated by nova-tech-build.github.io\n/satisfactory-symbol-db`)

        blueprint.objects.push(keySign.entity)
      }

      const z = Math.floor(signIndex / this.SIGNS_PER_BP_ROW)

      const text =
          row1.map(p => String.fromCodePoint(p)).join('') + '\n' +
          row2.map(p => String.fromCodePoint(p)).join('');

      const sign = keySign
        .withShiftZ(this.SIGN_HEIGHT * z)
        .withShiftX(-this.SIGN_WIDTH * (signIndex % this.SIGNS_PER_BP_ROW))
        .withText(text)

      blueprint.objects.push(sign.entity)

      if (blueprint.objects.length >= this.SIGNS_PER_BP) {
        yield blueprint
        blueprint = keySign = null
        bpIndex++
      }

      signIndex++
    }

    if (blueprint) {
      yield blueprint
    }
  }

  pointsToRows(points: number[]): number[][] {
    // trivial chunking for now
    const result: number[][] = []
    const maxPerRow = 18

    for (let i = 0; i < points.length; i += maxPerRow) {
      result.push(points.slice(i, i + maxPerRow))
    }
    return result
  }
}


export class BpZip
{
  public readonly jsZip: JSZip
  constructor() {
    this.jsZip = new JSZip()
  }

  add(name: string, blueprint: Blueprint): void {
    let sbpHeader: Uint8Array = new Uint8Array(0)
    const sbpBodyChunks: Uint8Array[] = []

    const summary = Parser.WriteBlueprintFiles(blueprint,
      header => { sbpHeader = header },
      chunk => { sbpBodyChunks.push(chunk) })

    this.jsZip.file(name + '.sbp', Buffer.concat([sbpHeader, ...sbpBodyChunks]))
    this.jsZip.file(name + '.sbpcfg', summary.configFileBinary)
  }

  async generateAsyncBlob(): Promise<Blob> {
    return this.jsZip.generateAsync({
      type: 'blob',
    })
  }
}
